In [183]:
import pandas as pd
from sklearn import datasets
df = datasets.load_wine()

In [184]:
dir(df)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [185]:
ndf = pd.DataFrame(df.data,columns=df.feature_names)

In [186]:
ndf["Target"]= df.target

In [187]:
ndf.head(3)

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   

   od280/od315_of_diluted_wines  proline  Target  
0                          3.92   1065.0       0  
1                          3.40   1050.0       0  
2                          3.17   1185.0       0

In [188]:
X = ndf.drop(["Target"],axis=1)
y = ndf.Target

In [189]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30,random_state=100)

In [190]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [191]:
model.fit(X_train, y_train)

GaussianNB()

In [192]:
model.predict(X_test)

array([1, 2, 0, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 2, 2, 0, 2, 0, 1, 0, 2, 0,
       1, 1, 0, 0, 1, 1, 1, 2, 2, 1, 0, 1, 2, 2, 1, 1, 2, 2, 0, 2, 2, 2,
       0, 2, 2, 2, 0, 0, 0, 1, 0, 1])

In [193]:
model.score(X_test,y_test)

1.0

In [194]:
from sklearn.naive_bayes import MultinomialNB
model2 = MultinomialNB()

In [195]:
model2.fit(X_train, y_train)

MultinomialNB()

In [98]:
model2.predict(X_train)

array([1, 2, 0, 0, 1, 0, 2, 2, 0, 1, 1, 2, 1, 0, 1, 2, 0, 0, 0, 1, 2, 1,
       0, 0, 0, 2, 1, 2, 1, 1, 2, 0, 1, 0, 2, 2, 0, 1, 1, 0, 2, 2, 1, 0,
       0, 2, 0, 0, 2, 2, 2, 0, 2, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       2, 2, 0, 2, 2, 2, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 2, 1, 0, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 0, 2, 1, 2,
       2, 0, 0, 1, 0, 1, 1, 2, 1, 1, 1, 1, 0, 0])

In [99]:
model2.score(X_test,y_test)

0.7777777777777778

In [132]:
df = pd.read_csv("spam.csv")

In [133]:
a = pd.get_dummies(df["Category"])

In [134]:
df = pd.concat([df,a],axis=1)

In [135]:
df.drop(["Category"],axis=1,inplace=True)

In [136]:
df.drop(["ham"],axis=1,inplace=True)

In [137]:
df

Message  spam
0     Go until jurong point, crazy.. Available only ...     0
1                         Ok lar... Joking wif u oni...     0
2     Free entry in 2 a wkly comp to win FA Cup fina...     1
3     U dun say so early hor... U c already then say...     0
4     Nah I don't think he goes to usf, he lives aro...     0
...                                                 ...   ...
5567  This is the 2nd time we have tried 2 contact u...     1
5568               Will ü b going to esplanade fr home?     0
5569  Pity, * was in mood for that. So...any other s...     0
5570  The guy did some bitching but I acted like i'd...     0
5571                         Rofl. Its true to its name     0

[5572 rows x 2 columns]

In [161]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.30,random_state=100)

In [168]:
from sklearn.feature_extraction.text import CountVectorizer

In [169]:
a = CountVectorizer()

In [175]:
b = a.fit_transform(X_train.values)

<3900x7174 sparse matrix of type '<class 'numpy.int64'>'
	with 52098 stored elements in Compressed Sparse Row format>

In [174]:
b.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [176]:
from sklearn.naive_bayes import MultinomialNB
model3 = MultinomialNB()
model3.fit(b,y_train)

MultinomialNB()

In [179]:
emails = ['Hey can we get together to get football match tomorrow?',"Upto 20% discount on parking,exclusive offer just for you. Don't miss the reward!"]

In [180]:
c = model3.transform(emails)

In [182]:
model3.predict(c)

array([0, 1], dtype=uint8)